### ISSUE TITLE
Create All workouts page

### ISSUE THREAD

**Issue by RetiredHedgehog** [Doroshkeviches/RS-Clone#42]
All workouts page contains all [predefined](https://github.com/Doroshkeviches/RS-Clone/issues/43) and [user](https://github.com/Doroshkeviches/RS-Clone/issues/45) created workouts and a button to create user workouts.

**Comment by JaneEllison** [comment]
![Image](https://user-images.githubusercontent.com/65969334/217874429-ad481419-4f05-426c-be64-56a17eb20b28.png)
