### ISSUE TITLE
Create Workout page

### ISSUE THREAD

**Issue by RetiredHedgehog** [Doroshkeviches/RS-Clone#43]
Workout page should consist of:
- List of exercises with a summary and rest periods between exercises
- Overview of the current exercise
- ? Button on the current exercise, that leads to [Exercise page](https://github.com/Doroshkeviches/RS-Clone/issues/41)
- Start/Stop/Pause button
- Timer

Upon clicking Start button, the timer starts. After the timer for current exercise runs out, current exercise changes, timer resets.

After completing the full exercise, [Workout completion page](https://github.com/Doroshkeviches/RS-Clone/issues/44) is shown.

**Comment by JaneEllison** [comment]
![Image](https://user-images.githubusercontent.com/65969334/217874092-620bf766-9206-4fd8-9bad-427a3480125c.png)
