### ISSUE TITLE
Investigate free fitness API

### ISSUE THREAD

**Issue by JaneEllison** [Doroshkeviches/RS-Clone#5]
Search fitness API and provide a few variants with pluses and minuses to discuss.

**Comment by Doroshkeviches** [comment]
https://www.nutritionix.com/database   -  Nutritional Tracking API

**Comment by Doroshkeviches** [comment]
https://api-ninjas.com/api/exercises - Exercises API

**Comment by RetiredHedgehog** [comment]
https://wger.de/api/v2/video/?limit=78
This API has SOME videos (78 in total) of  varying quality.

**Comment by Doroshkeviches** [comment]
https://rapidapi.com/mortimerbrian135/api/exerciseapi3/

**Comment by Doroshkeviches** [comment]
https://api-ninjas.com/profile
